import { createHash } from 'node:crypto'; import { ComponentRelationService } from '../../core/component-relations/service.js'; import { ComponentType } from '../../core/component-relations/types.js'; import { GlpiClient } from './glpi-client.js';
const FIELDS:Record<ComponentType,string>={DeviceMotherboard:'devicemotherboards_id',DeviceProcessor:'deviceprocessors_id',DeviceMemory:'devicememories_id',DeviceHardDrive:'deviceharddrives_id',DeviceNetworkCard:'devicenetworkcards_id',DeviceGraphicCard:'devicegraphiccards_id',DeviceSoundCard:'devicesoundcards_id',DeviceDrive:'devicedrives_id',DevicePowerSupply:'devicepowersupplies_id',DeviceBattery:'devicebatteries_id',DeviceFirmware:'devicefirmwares_id',DeviceCase:'devicecases_id',DeviceControl:'devicecontrols_id',DeviceCamera:'devicecameras_id',DeviceSensor:'devicesensors_id',DeviceSimcard:'devicesimcards_id',DevicePci:'devicepcis_id',DeviceGeneric:'devicegenerics_id'};
const forbidden=/^(id|itemtype|items_id|device[a-z]+_id|date_creation|date_mod|is_deleted)$/i; function safe(v:Record<string,unknown>){for(const k of Object.keys(v))if(forbidden.test(k))throw new Error(`Component relation field ${k} is controlled by GLPI`);return v;} function n(v:unknown){return Number(v??0);} function stable(v:unknown):unknown{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,stable(x)]));return v;} function hash(v:unknown){return createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');}
export class LegacyComponentRelationService implements ComponentRelationService { constructor(private readonly client:GlpiClient){} private type(c:ComponentType){return `Item_${c}`;} private async all(t:string){const out:Record<string,unknown>[]=[];for(let s=0;s<50000;s+=1000){const p=await this.client.getItems<Record<string,unknown>>(t,{range:`${s}-${s+999}`,expand_dropdowns:false});out.push(...p);if(p.length<1000)break;}return out;}
 async list(i:{itemtype:string;assetId:number;componentType:ComponentType}){await this.client.getItem(i.itemtype,i.assetId);const relations=(await this.all(this.type(i.componentType))).filter(r=>r.itemtype===i.itemtype&&n(r.items_id)===i.assetId);return{itemtype:i.itemtype,asset_id:i.assetId,component_type:i.componentType,relations,returned:relations.length,complete:true,modifies_data:false};}
 async usage(i:{componentType:ComponentType;componentId:number}){await this.client.getItem(i.componentType,i.componentId);const field=FIELDS[i.componentType];const relations=(await this.all(this.type(i.componentType))).filter(r=>n(r[field])===i.componentId);return{component_type:i.componentType,component_id:i.componentId,relations,usage_count:relations.length,can_delete_definition:relations.length===0,complete:true,modifies_data:false};}
 async attach(i:{itemtype:string;assetId:number;componentType:ComponentType;componentId:number;fields:Record<string,unknown>;correlationId:string}){await Promise.all([this.client.getItem(i.itemtype,i.assetId),this.client.getItem(i.componentType,i.componentId)]);const field=FIELDS[i.componentType],type=this.type(i.componentType);const exact=(await this.all(type)).find(r=>r.itemtype===i.itemtype&&n(r.items_id)===i.assetId&&n(r[field])===i.componentId&&String(r.serial??'')===String(i.fields.serial??''));if(exact)return{success:true,idempotent:true,relation:exact,correlation_id:i.correlationId};const created=await this.client.createItem(type,{itemtype:i.itemtype,items_id:i.assetId,[field]:i.componentId,...safe(i.fields)});return{success:true,operation:'attach_component',relation_id:created.id,after:await this.client.getItem(type,created.id),correlation_id:i.correlationId,verification_status:'verified'};}
 async update(i:{componentType:ComponentType;relationId:number;fields:Record<string,unknown>;expectedAssetId?:number;correlationId:string}){const type=this.type(i.componentType),before=await this.client.getItem<Record<string,unknown>>(type,i.relationId,{expand_dropdowns:false});if(i.expectedAssetId!==undefined&&n(before.items_id)!==i.expectedAssetId)throw new Error('Component relation owner changed concurrently');await this.client.updateItem(type,i.relationId,safe(i.fields));return{success:true,operation:'update_component_relation',before,after:await this.client.getItem(type,i.relationId,{expand_dropdowns:false}),correlation_id:i.correlationId,verification_status:'verified'};}
 async previewDetach(i:{componentType:ComponentType;relationId:number}){const type=this.type(i.componentType),current=await this.client.getItem(type,i.relationId);const plan={component_type:i.componentType,relation_id:i.relationId,itemtype:type,current,operation:'detach_relation_only'};return{...plan,preview_fingerprint:hash(plan),applicable:true,modifies_data:false};}
 async detach(i:{componentType:ComponentType;relationId:number;previewFingerprint:string;confirmation:string;correlationId:string}){const p=await this.previewDetach(i) as Record<string,unknown>;if(p.preview_fingerprint!==i.previewFingerprint)throw new Error('Component detach preview is stale');await this.client.deleteItem(String(p.itemtype),i.relationId,true);return{success:true,operation:'detach_component',relation_id:i.relationId,before:p.current,correlation_id:i.correlationId,verification_status:'request_succeeded'};}}
