import test from 'node:test';
import assert from 'node:assert/strict';
import { LegacyNetworkTopologyService } from '../src/api/legacy/network-topology.js';
import { networkLinkRemoveSchema, portConnectSchema } from '../src/core/network-topology/schemas.js';
import { toolAnnotations } from '../src/core/tool-annotations.js';
function fixture(seed: Record<string, any[]>) { const writes: any[] = []; return { writes, client: {
  async getItems(type: string) { return (seed[type] ?? []).map((r) => ({ ...r })); },
  async getItem(type: string, id: number) { const r = (seed[type] ?? []).find((x) => x.id === id); if (!r) throw new Error('not found'); return { ...r }; },
  async createItem(type: string, payload: any) { seed[type] ??= []; const id = 100 + seed[type].length; seed[type].push({ id, ...payload }); writes.push(['create', type, payload]); return { id }; },
  async updateItem(type: string, id: number, payload: any) { Object.assign((seed[type] ?? []).find((x) => x.id === id), payload); writes.push(['update', type, id, payload]); },
  async deleteItem(type: string, id: number) { seed[type] = (seed[type] ?? []).filter((x) => x.id !== id); writes.push(['delete', type, id]); },
} as any }; }
test('port updates preserve relations and enforce expected owner', async () => { const mock = fixture({ Computer: [{ id: 1 }], NetworkPort: [{ id: 2, itemtype: 'Computer', items_id: 1, name: 'eth0' }] }); const service = new LegacyNetworkTopologyService(mock.client); const result: any = await service.updatePort({ id: 2, fields: { name: 'lan0' }, expectedAssetId: 1, correlationId: 'c' }); assert.deepEqual(result.preserved_relations, ['ip_addresses', 'vlans', 'port_connections']); await assert.rejects(() => service.updatePort({ id: 2, fields: { name: 'x' }, expectedAssetId: 9, correlationId: 'c' }), /owner changed/); });
test('VLAN attach is idempotent and verified', async () => { const mock = fixture({ NetworkPort: [{ id: 2 }], Vlan: [{ id: 3 }], NetworkPort_Vlan: [] }); const service = new LegacyNetworkTopologyService(mock.client); const first: any = await service.attachVlan({ portId: 2, vlanId: 3, tagged: true, correlationId: 'c' }); assert.equal(first.verification_status, 'verified'); const second: any = await service.attachVlan({ portId: 2, vlanId: 3, tagged: true, correlationId: 'c' }); assert.equal(second.idempotent, true); });
test('physical connections reject occupied ports and remove only fingerprinted relation', async () => { const mock = fixture({ NetworkPort: [{ id: 1 }, { id: 2 }, { id: 3 }], NetworkPort_NetworkPort: [] }); const service = new LegacyNetworkTopologyService(mock.client); const connected: any = await service.connectPorts({ portId: 1, peerPortId: 2, correlationId: 'c' }); await assert.rejects(() => service.connectPorts({ portId: 1, peerPortId: 3, correlationId: 'c' }), /already has/); const preview: any = await service.previewRemoveLink({ kind: 'port_connection', relationId: connected.relation_id }); await service.removeLink({ kind: 'port_connection', relationId: connected.relation_id, previewFingerprint: preview.preview_fingerprint, confirmation: 'I_HAVE_VERIFIED_THE_NETWORK_LINK_REMOVAL', correlationId: 'c' }); assert.equal(mock.writes.at(-1)[0], 'delete'); });
test('network schemas and annotations enforce guards', () => { assert.throws(() => portConnectSchema.parse({ port_id: 1, peer_port_id: 1, correlation_id: '123e4567-e89b-42d3-a456-426614174000' })); assert.throws(() => networkLinkRemoveSchema.parse({ kind: 'vlan', relation_id: 1, preview_fingerprint: 'a'.repeat(64), confirmation: 'NO', correlation_id: '123e4567-e89b-42d3-a456-426614174000' })); assert.equal(toolAnnotations('glpi_remove_network_link').destructiveHint, true); });
test('IP attach reuses NetworkName and address idempotently', async () => { const mock = fixture({ NetworkPort: [{ id: 1 }], NetworkName: [], IPAddress: [] }); const service = new LegacyNetworkTopologyService(mock.client); const first: any = await service.attachIPAddress({ portId: 1, address: '192.0.2.10', networkName: 'host', correlationId: 'c' }); assert.equal(first.network_name_created, true); const second: any = await service.attachIPAddress({ portId: 1, address: '192.0.2.10', networkName: 'host', correlationId: 'c' }); assert.equal(second.idempotent, true); assert.equal(mock.writes.filter((w) => w[0] === 'create').length, 2); });
test('IP move checks expected parent and preserves source NetworkName', async () => { const mock = fixture({ NetworkPort: [{ id: 1 }, { id: 2 }], NetworkName: [{ id: 10, itemtype: 'NetworkPort', items_id: 1, name: 'old' }], IPAddress: [{ id: 20, itemtype: 'NetworkName', items_id: 10, name: '2001:db8::1' }] }); const service = new LegacyNetworkTopologyService(mock.client); await assert.rejects(() => service.moveIPAddress({ ipAddressId: 20, targetPortId: 2, expectedNetworkNameId: 99, correlationId: 'c' }), /changed concurrently/); const moved: any = await service.moveIPAddress({ ipAddressId: 20, targetPortId: 2, networkName: 'new', expectedNetworkNameId: 10, correlationId: 'c' }); assert.equal(moved.source_network_name_preserved, true); assert.notEqual(moved.after.items_id, 10); });
test('port deletion is blocked by every network dependency while IP deletion is fingerprinted', async () => { const mock = fixture({ NetworkPort: [{ id: 1 }], NetworkName: [{ id: 10, itemtype: 'NetworkPort', items_id: 1 }], IPAddress: [{ id: 20, itemtype: 'NetworkName', items_id: 10, name: '192.0.2.1' }], NetworkPort_Vlan: [{ id: 30, networkports_id: 1 }], NetworkPort_NetworkPort: [] }); const service = new LegacyNetworkTopologyService(mock.client); const portPreview: any = await service.previewDelete({ kind: 'network_port', id: 1 }); assert.equal(portPreview.applicable, false); await assert.rejects(() => service.delete({ kind: 'network_port', id: 1, previewFingerprint: portPreview.preview_fingerprint, confirmation: 'I_HAVE_VERIFIED_THE_NETWORK_OBJECT_DELETE', correlationId: 'c' }), /blocked/); const ipPreview: any = await service.previewDelete({ kind: 'ip_address', id: 20 }); await service.delete({ kind: 'ip_address', id: 20, previewFingerprint: ipPreview.preview_fingerprint, confirmation: 'I_HAVE_VERIFIED_THE_NETWORK_OBJECT_DELETE', correlationId: 'c' }); assert.equal(mock.writes.at(-1)[1], 'IPAddress'); });
