import { IPNetworkService } from './ip-networks/service.js';
import { TicketService } from './tickets/service.js';
import { InventoryPluginService } from './inventory-plugin/service.js';
import { SessionService } from './session/service.js';
import { ImportEntityRuleService } from './rules/service.js';
import { OrganizationService } from './organization/service.js';
import { DirectoryService } from './directory/service.js';
import { PrinterService } from './assets/service.js';
import { FormService } from './forms/service.js';
import { LocationIntegrityService } from './location-integrity/service.js';
import { UnmanagedReconciliationService } from './unmanaged-reconciliation/service.js';
import { AddressingSyncService } from './addressing-sync/service.js';
import { AssetImportRuleService } from './asset-import-rules/service.js';
import { InventoryInsightsService } from './inventory-insights/service.js';
import { CatalogService } from './catalog/service.js';
import { GovernanceService } from './governance/service.js';
import { NetworkTopologyService } from './network-topology/service.js';
import { ComponentRelationService } from './component-relations/service.js';
import { AssetSubobjectService } from './asset-subobjects/service.js';
import { ItemMetadataService } from './item-metadata/service.js';

export interface GlpiServices {
  tickets: TicketService;
  ipNetworks?: IPNetworkService;
  inventoryPlugin?: InventoryPluginService;
  session: SessionService;
  importEntityRules: ImportEntityRuleService;
  organization: OrganizationService;
  directory: DirectoryService;
  printers: PrinterService;
  forms: FormService;
  locationIntegrity: LocationIntegrityService;
  unmanagedReconciliation: UnmanagedReconciliationService;
  addressingSync: AddressingSyncService;
  assetImportRules: AssetImportRuleService;
  inventoryInsights: InventoryInsightsService;
  catalog: CatalogService;
  governance: GovernanceService;
  networkTopology: NetworkTopologyService;
  componentRelations: ComponentRelationService;
  assetSubobjects: AssetSubobjectService;
  itemMetadata: ItemMetadataService;
}
